//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsw2025Tpi.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dsw2025Tpi.Shared.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las credenciales ingresadas son inválidas. Verifique su usuario y contraseña..
        /// </summary>
        internal static string AUTH_INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("AUTH_INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo crear el usuario. Verifique que el usuario y correo electrónico sean válidos y únicos..
        /// </summary>
        internal static string AUTH_USER_CREATION_FAILED {
            get {
                return ResourceManager.GetString("AUTH_USER_CREATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente ya se encuentra inactivo..
        /// </summary>
        internal static string CUSTOMER_ALREADY_INACTIVE {
            get {
                return ResourceManager.GetString("CUSTOMER_ALREADY_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente está inactivo y no puede operar, revise su situación..
        /// </summary>
        internal static string CUSTOMER_INACTIVE {
            get {
                return ResourceManager.GetString("CUSTOMER_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email del cliente no es válido..
        /// </summary>
        internal static string CUSTOMER_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("CUSTOMER_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del cliente no es válido..
        /// </summary>
        internal static string CUSTOMER_INVALID_NAME {
            get {
                return ResourceManager.GetString("CUSTOMER_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de teléfono del cliente no es válido..
        /// </summary>
        internal static string CUSTOMER_INVALID_PHONE {
            get {
                return ResourceManager.GetString("CUSTOMER_INVALID_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden ya se encuentra finalizada y no puede ser modificada. Las órdenes entregadas o canceladas no pueden cambiar de estado..
        /// </summary>
        internal static string ORDER_ALREADY_FINALIZED {
            get {
                return ResourceManager.GetString("ORDER_ALREADY_FINALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock insuficiente para completar la orden..
        /// </summary>
        internal static string ORDER_INSUFFICIENT_STOCK {
            get {
                return ResourceManager.GetString("ORDER_INSUFFICIENT_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección de facturación no es válida. Debe proporcionar una dirección válida..
        /// </summary>
        internal static string ORDER_INVALID_BILLING_ADDRESS {
            get {
                return ResourceManager.GetString("ORDER_INVALID_BILLING_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente especificado para la orden no es válido. Verifique que el ID del cliente sea correcto..
        /// </summary>
        internal static string ORDER_INVALID_CUSTOMER {
            get {
                return ResourceManager.GetString("ORDER_INVALID_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección de envío no es válida. Debe proporcionar una dirección válida..
        /// </summary>
        internal static string ORDER_INVALID_SHIPPING_ADDRESS {
            get {
                return ResourceManager.GetString("ORDER_INVALID_SHIPPING_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado de la orden proporcionado no es válido. Estados válidos: Pending, Processing, Shipped, Delivered, Cancelled..
        /// </summary>
        internal static string ORDER_INVALID_STATUS {
            get {
                return ResourceManager.GetString("ORDER_INVALID_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La transición de estado solicitada no es válida. Verifique el flujo de estados permitido para la orden..
        /// </summary>
        internal static string ORDER_INVALID_STATUS_TRANSITION {
            get {
                return ResourceManager.GetString("ORDER_INVALID_STATUS_TRANSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden solicitada no existe..
        /// </summary>
        internal static string ORDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ORDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden ya se encuentra en el estado especificado. No es necesario realizar la transición..
        /// </summary>
        internal static string ORDER_STATUS_ALREADY_SET {
            get {
                return ResourceManager.GetString("ORDER_STATUS_ALREADY_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden no contiene elementos. Agregue al menos un producto a la orden antes de continuar..
        /// </summary>
        internal static string ORDER_WITHOUT_ITEMS {
            get {
                return ResourceManager.GetString("ORDER_WITHOUT_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precio unitario del elemento en la orden no es válido. Debe ser un valor mayor a cero..
        /// </summary>
        internal static string ORDERITEM_INVALID_PRICE {
            get {
                return ResourceManager.GetString("ORDERITEM_INVALID_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto especificado para el elemento de la orden no es válido. El ID del producto no puede estar vacío..
        /// </summary>
        internal static string ORDERITEM_INVALID_PRODUCT {
            get {
                return ResourceManager.GetString("ORDERITEM_INVALID_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del producto es obligatorio para registrar el ítem de la orden..
        /// </summary>
        internal static string ORDERITEM_INVALID_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("ORDERITEM_INVALID_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad del elemento en la orden no es válida. Debe ser un valor mayor a cero..
        /// </summary>
        internal static string ORDERITEM_INVALID_QUANTITY {
            get {
                return ResourceManager.GetString("ORDERITEM_INVALID_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un producto con {0} &apos;{1}&apos;..
        /// </summary>
        internal static string PRODUCT_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("PRODUCT_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede realizar operaciones sobre un producto inactivo. Active el producto antes de continuar..
        /// </summary>
        internal static string PRODUCT_INACTIVE {
            get {
                return ResourceManager.GetString("PRODUCT_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock insuficiente para realizar la operación. La cantidad solicitada excede el inventario disponible..
        /// </summary>
        internal static string PRODUCT_INSUFFICIENT_STOCK {
            get {
                return ResourceManager.GetString("PRODUCT_INSUFFICIENT_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código interno del producto no es válido. Debe ser un valor no vacío..
        /// </summary>
        internal static string PRODUCT_INVALID_INTERNAL_CODE {
            get {
                return ResourceManager.GetString("PRODUCT_INVALID_INTERNAL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del producto no es válido. Debe ser un valor no vacío..
        /// </summary>
        internal static string PRODUCT_INVALID_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precio del producto no es válido. Debe ser un valor mayor a cero..
        /// </summary>
        internal static string PRODUCT_INVALID_PRICE {
            get {
                return ResourceManager.GetString("PRODUCT_INVALID_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad del producto no es válida. Debe ser un valor mayor a cero..
        /// </summary>
        internal static string PRODUCT_INVALID_QUANTITY {
            get {
                return ResourceManager.GetString("PRODUCT_INVALID_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El SKU del producto no es válido. Debe ser un valor no vacío..
        /// </summary>
        internal static string PRODUCT_INVALID_SKU {
            get {
                return ResourceManager.GetString("PRODUCT_INVALID_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El stock del producto no es válido. Debe ser un valor mayor o igual a cero..
        /// </summary>
        internal static string PRODUCT_INVALID_STOCK {
            get {
                return ResourceManager.GetString("PRODUCT_INVALID_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto solicitado no existe..
        /// </summary>
        internal static string PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_FOUND", resourceCulture);
            }
        }
    }
}
